-- =====================================================================
--  autozona.sql — Zona automática en la PPP desde el barrio (v4.99, server-side)
--
--  Antes la ZONA de cada pedido se cargaba a mano en el Excel y se levantaba a
--  PPP_Programacion_Diaria. Ahora Supabase la deriva SOLA del barrio: el Excel
--  puede dejar la columna zona en blanco.
--
--  Dato que lo habilita: el barrio determina la zona de forma LIMPIA (34 barrios
--  en el histórico, 0 ambiguos — ningún barrio cae en 2 zonas).
--
--  Componentes:
--   • Tabla public."Zonas_Barrios" (barrio_norm PK · zona · creado): mapeo
--     barrio→zona (la "fuente de verdad"). RLS on, anon SELECT (read-only).
--   • public._norm_barrio(text) IMMUTABLE: normaliza el barrio para el match =
--     minúsculas + SIN TILDES (translate áéíóúü→aeiouu) + espacios colapsados.
--     ⚠ Las tildes importan: "Esteban Echeverría" vs "Esteban Echeverria" deben
--     matchear (si no, no clasifica → queda sin zona).
--   • public.ppp_autozona() + trigger trg_ppp_autozona BEFORE INSERT OR UPDATE en
--     PPP_Programacion_Diaria: si el pedido llega SIN zona y CON barrio, busca el
--     barrio normalizado en Zonas_Barrios y completa new.zona. NO pisa una zona
--     ya cargada (solo completa la vacía). SECURITY DEFINER para leer el mapeo sin
--     depender de la RLS del rol que hace el insert (importador del Excel/anon).
--
--  Bootstrap (1 vez): se pobló Zonas_Barrios del histórico
--    insert into "Zonas_Barrios"(barrio_norm,zona)
--      select _norm_barrio(barrio), max(btrim(zona)) from "PPP_Programacion_Diaria"
--      where zona<>'' and barrio<>'' group by _norm_barrio(barrio);
--  y se hizo backfill de los pedidos viejos sin zona cuyo barrio ya estaba mapeado.
--
--  Flujo de mantenimiento (barrio NUEVO, no mapeado) — DOS caminos según el Excel:
--   · Si el Excel TRAE zona (geográfica 'Zona %') → el trigger la APRENDE solo:
--     inserta barrio→zona en Zonas_Barrios (ON CONFLICT DO NOTHING, el 1º gana) y de
--     ahí en más deriva automático. Nunca más "sin zona" para ese barrio. NO aprende
--     Super/Retira/Expo (son TIPO DE CLIENTE, no barrio). Cerró el hueco que dejaba
--     pedidos con zona-en-Excel pero barrio desconocido (ej. V.Devoto/Villa Bosch):
--     antes NO saltaba `ppp_sin_zona` (tenían zona) y NADIE aprendía el barrio → el
--     agrupador del monitor los tiraba a "sin zona".
--   · Si el Excel viene SIN zona y el barrio es desconocido → no hay nada que derivar
--     ni aprender → queda sin zona → salta la alerta `ppp_sin_zona` (ver
--     ppp_sin_zona.sql) por Telegram para que un humano lo cargue.
--  (Pendiente opcional: mini-UI admin para asignar zona a barrios nuevos sin SQL —
--   el `⚠ asignar…` de la fila hoy guarda un override LOCAL, no Supabase.)
--
--  Migraciones aplicadas: `ppp_autozona_barrio` (tabla+trigger) +
--  `ppp_autozona_normaliza_tildes` (_norm_barrio sin tildes + trigger) +
--  `ppp_autozona_aprende_barrio_nuevo` (v6.37: el trigger además APRENDE el barrio
--  nuevo cuando el Excel trae zona geográfica). Bootstrap del diccionario re-corrido
--  en v6.37: 26 barrios geográficos que faltaban → 0 barrios geo sin mapear.
-- =====================================================================
