-- =====================================================================
--  reconciliar_pipeline_stock.sql — Pipeline de stock SERVER-SIDE (v4.99)
--
--  PROBLEMA (root cause): "Pickeados" y "A facturar" mostraban 0 aunque
--  hubiera pedidos pickeados/armados, y la GÓNDOLA nunca bajaba por el picking.
--  TODO eso era UN SOLO bug:
--    • El CHECK `Movimientos_Stock_deposito_check` NO incluía
--      `separar_pedidos`, `a_facturar` ni `excedente` (solo a_guardar/
--      terminado/racks/insumos).
--    • El cliente `stockBajaPicking` arma el picking como UN batch
--      `stockMove([terminado−, separar_pedidos+])` → un solo POST a PostgREST.
--    • La fila `separar_pedidos` violaba el CHECK → PostgREST rechazaba TODO
--      el batch con HTTP 400.
--    • `stockMove` se TRAGA los 4xx (`if (r.ok || (status>=400 && <500)) return`)
--      → fallo silencioso: ni se descontaba góndola ni se llenaba separar.
--  Además los equipos de picking corren una app vieja (TWA) que ni siquiera
--  intentaba el pipeline.
--
--  FIX (este archivo / migraciones aplicadas):
--   1) `movimientos_stock_deposito_check_pipeline`: el CHECK ahora permite
--      terminado, excedente, separar_pedidos, a_facturar, a_guardar, racks, insumos.
--      (Desbloquea el pipeline tanto del cliente como del server.)
--   2) `reconciliar_pipeline_stock()` (migración `reconciliar_pipeline_stock`):
--      replica las 3 etapas del cliente, pero del lado del server, idempotente:
--        ETAPA 1 (PKC/TP): separar_pedidos(+picked) y baja EXCEDENTE-FIRST
--          (excedente− y el resto góndola−). Dedup por índice único (ver v5.76).
--        ETAPA 2 (TAP):    mueve el neto de separar_pedidos → a_facturar.
--        ETAPA 3 (factura): saca de a_facturar cuando la tanda está 100%
--          facturada (todos los NP de la PPP en Facturacion_NP).
--      Dedup por la existencia del movimiento (separar_pedidos / tipo='separado'
--      / tipo='facturado' por ref=tanda). Comparte los `tipo` con el cliente, así
--      si una app nueva sí corre el pipeline, los guards evitan doble conteo.
--      Sólo procesa tandas con actividad POST-cutoff (Stock_Config.cutoff_ts);
--      lo anterior ya está en el snapshot `inicial`. SECURITY DEFINER, revoke
--      anon/authenticated, grant service_role. Nunca lanza (devuelve texto).
--
--  CRON: jobid 22 `reconciliar-pipeline-stock`, `*/10 * * * *` (cada 10 min).
--    select cron.schedule('reconciliar-pipeline-stock','*/10 * * * *',
--      $$select public.reconciliar_pipeline_stock();$$);
--    (Registros_Produccion_Virgilio es chico → el scan cada 10 min es trivial.)
--    Mantiene Pickeados/A facturar al día desde los eventos sin depender de la
--    app vieja. El pipeline del cliente queda como "fast path" (instantáneo); el
--    cron es la red de seguridad para equipos con app vieja.
--
--  v5.76 — EL CRON ES EL ÚNICO ESCRITOR DEL PICKING. El "fast path" del cliente
--    (stockBajaPicking, TP) se DESACTIVÓ: el guard chequear-y-después-insertar no
--    es atómico y la cola offline del cliente (vir_stock_pend) abría una ventana en
--    la que el cron insertaba primero y el cliente duplicaba (separar +2×, góndola
--    −2×; se vio en C81B/C87A/C87F/C87H, ~486 cajas). Ahora el cliente NO toca el
--    stock del picking (solo emite el aviso SSG). Se limpiaron a mano las filas de
--    picking del cliente en esas 4 tandas (C81B/C87A ya facturadas → además ajuste
--    compensatorio en separar_pedidos, tipo='ajuste_doble_pipeline').
--    v5.76 (2ª parte) — DEDUP ATÓMICO + EXCEDENTE-FIRST:
--     (a) EXCEDENTE-FIRST portado a ETAPA 1: se baja primero de excedente y el resto
--         de góndola (window por artículo para no sobre-descontar el excedente si
--         dos tandas del mismo art entran en la misma corrida). No se pierde la
--         lógica que tenía el cliente.
--     (b) Índice único parcial `mov_stock_pipeline_dedup` UNIQUE
--         (upper(trim(ref)), upper(trim(cod_art)), deposito, tipo)
--         WHERE tipo IN ('picking','separado','facturado') → una sola fila por
--         (tanda, art, depósito, etapa). Mata la race para las 3 etapas a nivel DB.
--         Las 3 etapas del cron usan ON CONFLICT DO NOTHING; el cliente (que aún
--         escribe separado/facturado hasta el merge) choca y su 4xx se traga solo.
--         tipo va EN la clave porque en separar_pedidos conviven picking(+) y
--         separado(−).
--
--  BACKLOG RECONCILIADO (29/06): 6 tandas en vuelo, post-cutoff:
--    separar_pedidos (Pickeados) = 627  → C58C 108 + C58E 44 + C59C 475
--    a_facturar      (A facturar) = 442 → C58A 115 + C58B 247 + C58D 80
--    góndola: −634 sólo de las 3 sin descuento previo (C58A/C58E/C59C);
--             C58B/C58C/C58D ya tenían el descuento del seed manual.
--    Góndola quedó con sólo 2 artículos en −5 (despreciable).
--
--  v6.29 — FIX DOBLE-FACTURADO (a_facturar negativo). La ETAPA 3 agrupaba por
--    `ref` crudo y solo deduplicaba contra `facturado ref=tanda`. Pero el CLIENTE
--    factura por NP con `ref=tanda|NP` → el cron NO lo veía y volvía a facturar
--    (`ref=tanda`) → DOBLE facturado → a_facturar quedaba NEGATIVO (restaba stock
--    real del total). Se veía en 137 códigos / 364 tandas / 1.417 cajas, 100%
--    explicado por este pipeline. Fix (migración `pipeline_etapa3_facturado_por_
--    tanda_evita_doble`): la ETAPA 3 ahora calcula el neto y el dedup POR TANDA,
--    contando también los facturados del cliente (`ref=tanda|NP` → normaliza con
--    split_part(ref,'|',1)). Solo drena el remanente REAL: si el cliente ya lo
--    sacó, net<=0 y no hace nada → nunca más duplica. Los 1.417 ya colgados se
--    compensaron con ajustes trazables (tipo='ajuste', legajo='reconcilia', uno
--    por tanda, llevando cada a_facturar-por-tanda a 0). ETAPA 1 y 2 sin cambios.
--
--  La definición viva de la función está en la migración homónima en Supabase.
--  Este archivo es la documentación del diseño (convención de sql/).
-- =====================================================================
